### ISSUE TITLE
Why does labjackpython package still enforce python=2.7?

### ISSUE THREAD

**Issue by paquitaz** [labjack/LabJackPython#102]
Even though the setup.py has all versions pf python listed, after python setup.py install I tried to include it in a conda environment and got this error: 

$ conda env create -f environment.yml
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - labjackpython -> python 2.7*
  - python 3*
Use "conda info <package>" to see the dependencies for each package.

**Comment by mnaberez** [comment]
If you are trying to install a release version from [PyPI](https://pypi.python.org/pypi/LabJackPython), that would explain why it is shown as incompatible with Python 3.  A version of LabJackPython that supports Python 3 has not been released to PyPI yet.  

The master branch has work-in-progress support for Python 3.  That is why [`setup.py` on the master branch](https://github.com/labjack/LabJackPython/blob/c86f48d20d3ea28fac6d1d0f12961abbf9dde321/setup.py#L22-L30) indicates support for Python 3.

The latest version released to PyPI at this time is [LabJackPython 1.201505](https://pypi.python.org/pypi/LabJackPython/1.201505).  It only supports Python 2.x.  That's what is shown by its classifers and enforced by the check in `setup.py`.  Here's the Python version classifiers in the release version:

```
$ wget https://pypi.python.org/packages/eb/97/e1e174bcd1e24df249c2a97a8a32d5632439d08eab4acfb645e75b253079/LabJackPython-1.201505.zip
$ unzip -q LabJackPython-1.201505.zip
$ grep 'Programming Language' LabJackPython-1.201505/setup.py 
    'Programming Language :: Python',
    'Programming Language :: Python :: 2',
    'Programming Language :: Python :: 2.5',
    'Programming Language :: Python :: 2.6',
    'Programming Language :: Python :: 2.7',
$
```

**Comment by davelopez01** [comment]
The issue was worked out over email.

conda-forge currently provides the LabJackPython 04-24-2014 release for Python 2.7. That version, along with the last "stable" release of 05-26-2015 (which is also on PyPI as version 1.201505), do not support Python 3. Keep in mind that LabJack does not maintain Anaconda/conda packages.

If Python 3 support is needed, use the version from the current master branch on GitHub, which is newer than the last 05-26-2015 release. Since it is not a conda package, you will need to install it with a package manager such as pip:

pip install https://github.com/labjack/LabJackPython/archive/master.zip

This can also be done by creating an conda environment (environment.yml file) with dependency:

 dependencies:
    - pip:
     - git+https://github.com/labjack/LabJackPython.git

**Comment by cxbrooks** [comment]
labjackpython 2.0.0 works for Python 3.x under macOS and Windows 10:

macOS Mojave 10.14.4:

```
bash-3.2$ pip3 --version
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
bash-3.2$ pip3 install labjackpython
Collecting labjackpython
  Downloading https://files.pythonhosted.org/packages/a8/7a/912edc61fb6158f0e061722ccee7fcdb912b76d7b696a0a\
68e83aad33a9c/LabJackPython-2.0.0-py2.py3-none-any.whl (111kB)
     |████████████████████████████████| 112kB 1.7MB/s
Installing collected packages: labjackpython
Successfully installed labjackpython-2.0.0
bash-3.2$ 
```
