### ISSUE TITLE
LabJack T7 Support

### ISSUE THREAD

**Issue by Jkillelea** [labjack/LabJackPython#123]
Hi there,

Would it be difficult to add LabJack T7 support to this library? I see that there's a separate installer for T7 drivers available at https://labjack.com/pages/support?doc=/software-driver/installer-downloads/ljm-software-installers-t4-t7-digit/, but it would be really nice to be able to interactively use this device. Since the `exodriver` / `liblabjack` already supports the T7, I was surprised to find that it's not officially in the Python library yet.

**Comment by sjarman28** [comment]
We have a separate Python package for T-series devices called [labjack-ljm](https://github.com/labjack/labjack-ljm-python).

Note that LabJackPython is set up primarily to communicate with UD devices using their low-level protocol over USB, and this protocol is different than T-series devices use (Modbus TCP). I think that it would take a notable amount of effort to add T-series device support to LabJackPython, and doing so does not make much sense for us since we have labjack-ljm available for T-series devices. The LJM library should be on par with or superior to LabJackPython and the Exodriver in most cases.

I would suggest seeing the "Moving forward from here" section of the T7 quickstart for an overview of our T7 support resources:
https://labjack.com/pages/support?doc=/quickstart/t7-quickstart-tutorial-platinum/t7-quickstart-overview/#section-header-two-laawv

**Comment by Jkillelea** [comment]
Ah, thanks, I understand the technical reasons for the difference. However, I think this is quite non-obvious to new users. I also do not like that the LJM library for the T series devices is closed-source. Would you be open to open-sourcing some of this software?

**Comment by sjarman28** [comment]
I added a quick note to the README about T-series device support (labjack-ljm).

We plan to keep LJM closed source for now, but we may reconsider making it open source in the future. Something to consider is that T-series devices are Modbus TCP servers, and they could be communicated directly via Modbus TCP if you do not want to use LJM. We have a small set of Modbus TCP examples on our website:
https://labjack.com/pages/support?doc=%2Fsoftware-driver%2Fexample-codewrappers%2Fpython%2F
